extends SceneTree

const HarnessScript := preload("res://tests/helpers/augment_test_harness.gd")
const VISUAL_REPORT_PATH := "res://docs/qa/augment-visual-differentiation.md"
const VISUAL_SIGNATURE_JSON_PATH := "res://docs/qa/augment-visual-signatures.json"
const COLLISION_THRESHOLD := 0.90
const CLUSTER_MIN_SIZE := 5

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var failures: Array[String] = []
	var harness = HarnessScript.new()
	failures.append_array(harness.setup(self, 616161))
	if not failures.is_empty():
		_finish(harness, failures)
		return

	var augments: Array = harness.get_augments()
	var signatures: Array[Dictionary] = []
	for augment_value in augments:
		var augment := augment_value as Resource
		if augment == null:
			continue
		var signature := harness.visual_signature_for_augment(augment)
		signature["augment_id"] = str(augment.get("id"))
		signature["display_name"] = str(augment.get("display_name"))
		signature["route_id"] = str(augment.get("route_id"))
		signature["rarity"] = str(augment.get("rarity"))
		signatures.append(signature)

	var missing := harness.visual_missing_identities(augments)
	var collisions := harness.visual_collision_pairs(augments, COLLISION_THRESHOLD)
	var clusters := harness.visual_homogenized_clusters(augments, CLUSTER_MIN_SIZE)

	for entry in missing:
		failures.append("%s missing visual identity: %s" % [str(entry.get("augment_id", "")), str(entry.get("reason", ""))])
	for entry in collisions:
		failures.append("visual collision %.2f: %s vs %s" % [float(entry.get("similarity", 0.0)), str(entry.get("left", "")), str(entry.get("right", ""))])
	for entry in clusters:
		failures.append("visual homogenized_cluster %s size=%d ids=%s" % [str(entry.get("cluster_key", "")), int(entry.get("size", 0)), entry.get("augment_ids", [])])

	harness.write_json_file(VISUAL_SIGNATURE_JSON_PATH, signatures)
	_write_report(harness, signatures, missing, collisions, clusters)
	print("augment_visual_differentiation wrote %s and %s" % [VISUAL_SIGNATURE_JSON_PATH, VISUAL_REPORT_PATH])
	_finish(harness, failures)

func _write_report(harness, signatures: Array[Dictionary], missing: Array[Dictionary], collisions: Array[Dictionary], clusters: Array[Dictionary]) -> void:
	var lines: Array[String] = []
	lines.append("# Augment Visual Differentiation")
	lines.append("")
	lines.append("Generated by `tests/smoke/augment_visual_differentiation.gd`.")
	lines.append("")
	lines.append("## Summary")
	lines.append("")
	lines.append("| Metric | Value |")
	lines.append("|---|---:|")
	lines.append("| Augments scanned | %d |" % signatures.size())
	lines.append("| Missing visual identity | %d |" % missing.size())
	lines.append("| Collision threshold | %.2f |" % COLLISION_THRESHOLD)
	lines.append("| Similarity collisions | %d |" % collisions.size())
	lines.append("| Homogenized clusters | %d |" % clusters.size())
	lines.append("")
	lines.append("The signature compares primary/secondary color buckets, shape family, animation family, spawn anchor, duration bucket, scale bucket, particle/trail usage, screen feedback and audio feedback. It is intentionally semantic rather than pixel-perfect, so it can run in headless smoke tests.")
	lines.append("")
	lines.append("## Missing visual identity")
	lines.append("")
	if missing.is_empty():
		lines.append("- none")
	else:
		for entry in missing:
			lines.append("- `%s`: %s" % [str(entry.get("augment_id", "")), str(entry.get("reason", ""))])
	lines.append("")
	lines.append("## Similarity collisions")
	lines.append("")
	if collisions.is_empty():
		lines.append("- none")
	else:
		for entry in collisions:
			var left_sig: Dictionary = entry.get("left_signature", {})
			var right_sig: Dictionary = entry.get("right_signature", {})
			lines.append("- `%.2f` `%s` ↔ `%s`" % [float(entry.get("similarity", 0.0)), str(entry.get("left", "")), str(entry.get("right", ""))])
			lines.append("  - left: `%s` / `%s` / `%s` / `%s`" % [str(left_sig.get("primary_color", "")), str(left_sig.get("shape_family", "")), str(left_sig.get("animation_type", "")), str(left_sig.get("particle_or_trail_usage", ""))])
			lines.append("  - right: `%s` / `%s` / `%s` / `%s`" % [str(right_sig.get("primary_color", "")), str(right_sig.get("shape_family", "")), str(right_sig.get("animation_type", "")), str(right_sig.get("particle_or_trail_usage", ""))])
	lines.append("")
	lines.append("## Homogenized clusters")
	lines.append("")
	if clusters.is_empty():
		lines.append("- none")
	else:
		for entry in clusters:
			lines.append("- `%s` size=%d: `%s`" % [str(entry.get("cluster_key", "")), int(entry.get("size", 0)), "`, `".join(_string_array(entry.get("augment_ids", [])))])
	lines.append("")
	lines.append("## Signatures")
	lines.append("")
	lines.append("| augment_id | route | rarity | primary | secondary | shape | animation | anchor | duration | scale | particle/trail | screen | audio |")
	lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
	for signature in signatures:
		lines.append("| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` |" % [
			str(signature.get("augment_id", "")),
			str(signature.get("route_id", "")),
			str(signature.get("rarity", "")),
			str(signature.get("primary_color", "")),
			str(signature.get("secondary_color", "")),
			str(signature.get("shape_family", "")),
			str(signature.get("animation_type", "")),
			str(signature.get("spawn_anchor", "")),
			str(signature.get("duration_bucket", "")),
			str(signature.get("scale_bucket", "")),
			str(signature.get("particle_or_trail_usage", "")),
			str(signature.get("screen_feedback_usage", "")),
			str(signature.get("audio_feedback_key", "")),
		])
	harness.write_markdown_file(VISUAL_REPORT_PATH, lines)

func _string_array(value: Variant) -> Array[String]:
	var result: Array[String] = []
	if value is Array:
		for item in value:
			result.append(str(item))
	return result

func _finish(harness, failures: Array[String]) -> void:
	if harness != null:
		harness.cleanup()
	if failures.is_empty():
		print("PASS: augment_visual_differentiation")
		quit(0)
		return
	for failure in failures:
		push_error(failure)
	quit(1)
