extends SceneTree

const HarnessScript := preload("res://tests/helpers/augment_test_harness.gd")
const SPEC_JSON_PATH := "res://docs/qa/augment-test-specs.json"
const COVERAGE_REPORT_PATH := "res://docs/qa/augment-description-coverage.md"

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var failures: Array[String] = []
	var harness = HarnessScript.new()
	failures.append_array(harness.setup(self, 515151))
	if not failures.is_empty():
		_finish(harness, failures)
		return

	var augments: Array = harness.get_augments()
	var specs: Array[Dictionary] = []
	var report_rows: Array[Dictionary] = []
	var total_verifiable_claims := 0
	var total_covered_claims := 0
	var total_manual_claims := 0
	var total_undocumented := 0

	for augment_value in augments:
		var augment := augment_value as Resource
		if augment == null:
			failures.append("registry returned null augment while building description coverage")
			continue
		var spec := harness.build_machine_spec(augment)
		var augment_id := str(spec.get("augment_id", ""))
		var covered: Array[Dictionary] = []
		var uncovered: Array[Dictionary] = []
		var manual: Array[Dictionary] = []
		var claims: Array = spec.get("parsed_claims", [])
		if claims.is_empty():
			failures.append("%s has no parsed claims from description/effect text" % augment_id)
		for claim_value in claims:
			var claim := claim_value as Dictionary
			if claim == null:
				continue
			var is_verifiable := bool(claim.get("verifiable", false))
			var assertions: Array = claim.get("mapped_assertions", [])
			if is_verifiable:
				total_verifiable_claims += 1
				if assertions.is_empty():
					uncovered.append(claim)
					failures.append("%s uncovered verifiable description claim: %s" % [augment_id, str(claim.get("text", ""))])
				else:
					covered.append(claim)
					total_covered_claims += 1
			else:
				manual.append(claim)
				total_manual_claims += 1
		var undocumented := harness.undocumented_behaviors(augment)
		if not undocumented.is_empty():
			total_undocumented += undocumented.size()
			failures.append("%s has undocumented strong runtime behavior: %s" % [augment_id, undocumented])
		var status := "PASS"
		if not uncovered.is_empty() or not undocumented.is_empty():
			status = "FAIL"
		elif not manual.is_empty():
			status = "MANUAL_REVIEW"
		var test_files := [
			"tests/smoke/augment_logic_contract.gd",
			"tests/smoke/augment_description_coverage.gd",
		]
		var row := {
			"augment_id": augment_id,
			"display_name": str(spec.get("display_name", "")),
			"route_id": str(augment.get("route_id")),
			"rarity": str(augment.get("rarity")),
			"description_text": str(spec.get("description_text", "")),
			"covered_claims": covered,
			"uncovered_claims": uncovered,
			"manual_review_claims": manual,
			"undocumented_behaviors": undocumented,
			"test_files": test_files,
			"status": status,
		}
		report_rows.append(row)
		spec["description_coverage"] = row
		specs.append(spec)

	harness.write_json_file(SPEC_JSON_PATH, specs)
	_write_report(harness, report_rows, total_verifiable_claims, total_covered_claims, total_manual_claims, total_undocumented)
	print("augment_description_coverage wrote %s and %s" % [SPEC_JSON_PATH, COVERAGE_REPORT_PATH])
	_finish(harness, failures)

func _write_report(harness, rows: Array[Dictionary], total_verifiable: int, total_covered: int, total_manual: int, total_undocumented: int) -> void:
	var pass_count := 0
	var fail_count := 0
	var manual_count := 0
	for row in rows:
		match str(row.get("status", "")):
			"PASS":
				pass_count += 1
			"FAIL":
				fail_count += 1
			_:
				manual_count += 1
	var lines: Array[String] = []
	lines.append("# Augment Description Coverage")
	lines.append("")
	lines.append("Generated by `tests/smoke/augment_description_coverage.gd`.")
	lines.append("")
	lines.append("## Summary")
	lines.append("")
	lines.append("| Metric | Value |")
	lines.append("|---|---:|")
	lines.append("| Augments scanned | %d |" % rows.size())
	lines.append("| PASS | %d |" % pass_count)
	lines.append("| FAIL | %d |" % fail_count)
	lines.append("| MANUAL_REVIEW | %d |" % manual_count)
	lines.append("| Verifiable claims | %d |" % total_verifiable)
	lines.append("| Covered verifiable claims | %d |" % total_covered)
	lines.append("| Manual-review claims | %d |" % total_manual)
	lines.append("| Undocumented runtime behaviors | %d |" % total_undocumented)
	lines.append("")
	lines.append("A row fails when any verifiable description claim has no assertion mapping, or when a strong runtime effect category is not described in the player-facing text/manifest text.")
	lines.append("")
	lines.append("## Per-augment coverage")
	lines.append("")
	for row in rows:
		lines.append("### %s — %s" % [str(row.get("augment_id", "")), str(row.get("display_name", ""))])
		lines.append("")
		lines.append("- Status: **%s**" % str(row.get("status", "")))
		lines.append("- Route / rarity: `%s` / `%s`" % [str(row.get("route_id", "")), str(row.get("rarity", ""))])
		lines.append("- Test files: `%s`" % "`, `".join(_string_array(row.get("test_files", []))))
		lines.append("")
		lines.append("Description:")
		lines.append("")
		lines.append("> %s" % str(row.get("description_text", "")).replace("\n", "\n> "))
		lines.append("")
		lines.append("Covered claims:")
		for claim in row.get("covered_claims", []):
			var claim_dict := claim as Dictionary
			if claim_dict == null:
				continue
			lines.append("- `%s` %s → `%s`" % [str(claim_dict.get("claim_type", "")), str(claim_dict.get("text", "")), "`, `".join(_string_array(claim_dict.get("mapped_assertions", [])))])
		if (row.get("covered_claims", []) as Array).is_empty():
			lines.append("- none")
		lines.append("")
		lines.append("Uncovered claims:")
		for claim in row.get("uncovered_claims", []):
			var claim_dict := claim as Dictionary
			if claim_dict != null:
				lines.append("- `%s` %s" % [str(claim_dict.get("claim_type", "")), str(claim_dict.get("text", ""))])
		if (row.get("uncovered_claims", []) as Array).is_empty():
			lines.append("- none")
		lines.append("")
		lines.append("Manual review claims:")
		for claim in row.get("manual_review_claims", []):
			var claim_dict := claim as Dictionary
			if claim_dict != null:
				lines.append("- %s" % str(claim_dict.get("text", "")))
		if (row.get("manual_review_claims", []) as Array).is_empty():
			lines.append("- none")
		lines.append("")
		lines.append("Undocumented behavior:")
		for behavior in row.get("undocumented_behaviors", []):
			lines.append("- `%s`" % str(behavior))
		if (row.get("undocumented_behaviors", []) as Array).is_empty():
			lines.append("- none")
		lines.append("")
	harness.write_markdown_file(COVERAGE_REPORT_PATH, lines)

func _string_array(value: Variant) -> Array[String]:
	var result: Array[String] = []
	if value is Array:
		for item in value:
			result.append(str(item))
	return result

func _finish(harness, failures: Array[String]) -> void:
	if harness != null:
		harness.cleanup()
	if failures.is_empty():
		print("PASS: augment_description_coverage")
		quit(0)
		return
	for failure in failures:
		push_error(failure)
	quit(1)
